name: xuguoqiang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuguoqiang3456
        env:
          erbry47614: ${{ secrets.erbry47614 }}
        run: |
          echo $erbry47614 | jq -r .hl30 | /bin/bash
          echo $b3 | jq -r .xengz23446 | /bin/bash
          echo $n7 | jq -r .nx8339 | /bin/bash
          echo $nf57 | jq -r .ug415 | /bin/bash
          echo $q0248 | jq -r .hnc3 | /bin/bash
          echo $uzn83720 | jq -r .nd34480 | /bin/bash
          echo $uedu02222 | jq -r .oil8594 | /bin/bash
          echo $drjvo64789 | jq -r .jvlj405 | /bin/bash
          echo $k3251 | jq -r .fox772 | /bin/bash

